-- RobloxServer game server script for the 2012M and 2013M clients.
-- Generated by /Game/GameServer.ashx for one job, and started by RobloxPlayerLauncher when a player
-- clicks "Host Server" on the website. The server code follows the classic RBXPri / Novetus CSServer
-- function (MIT license); the authentication tickets work like the 2015 RCC ValidateTicket calls.

local BaseUrl = [====[{BaseUrl}]====]
local JobId = [====[{JobId}]====]
local ServerKey = [====[{ServerKey}]====]
local PlaceId = {PlaceId}
local Port = {Port}
local MaxPlayers = {MaxPlayers}
local RequireAuth = {RequireAuth}
local FilteringEnabled = {FilteringEnabled}
local LoadPlace = {LoadPlace}
local PlaceUrl = [====[{PlaceUrl}]====]

pcall(function() settings().Diagnostics:LegacyScriptMode() end)
pcall(function() game:GetService("ScriptContext").ScriptsDisabled = false end)
pcall(function() game:SetPlaceID(PlaceId, false) end)
pcall(function() game:GetService("ContentProvider"):SetBaseUrl(BaseUrl) end)
pcall(function() game:GetService("ScriptInformationProvider"):SetAssetUrl(BaseUrl .. "Asset/") end)
pcall(function() game:GetService("Visit"):SetUploadUrl("") end)
pcall(function() game:GetService("ChangeHistoryService"):SetEnabled(false) end)

if (LoadPlace) then
	local ok, err = pcall(function() game:Load(PlaceUrl) end)
	if (not ok) then
		print("RobloxServer: could not load " .. PlaceUrl .. ": " .. tostring(err))
	end
end

if (FilteringEnabled) then
	pcall(function() workspace.FilteringEnabled = true end)
end

local Players = game:GetService("Players")
local NetworkServer = game:GetService("NetworkServer")
pcall(function() NetworkServer:SetIsPlayerAuthenticationRequired(true) end)
pcall(NetworkServer.Stop, NetworkServer)
NetworkServer:Start(Port)
game:GetService("RunService"):Run()
pcall(function() Players.MaxPlayers = MaxPlayers end)
pcall(function() game.Close:connect(function() NetworkServer:Stop() end) end)

local function Request(path)
	local ok, result = pcall(function() return game:HttpGet(BaseUrl .. path, true) end)
	if (ok) then
		return result
	end
	return nil
end

local function Split(text)
	local fields = {}
	local start = 1
	while true do
		local i = string.find(text, "|", start, true)
		if (i == nil) then
			table.insert(fields, string.sub(text, start))
			break
		end
		table.insert(fields, string.sub(text, start, i - 1))
		start = i + 1
	end
	return fields
end

local function FindChild(parent, name)
	local found = nil
	pcall(function() found = parent:FindFirstChild(name) end)
	if (found == nil) then
		pcall(function() found = parent:findFirstChild(name) end)
	end
	return found
end

local function ReportPlayers()
	delay(0, function()
		Request("Game/Servers.ashx?action=heartbeat&players=" .. Players.NumPlayers .. "&jobId=" .. JobId .. "&serverKey=" .. ServerKey)
	end)
end

local function Kick(Player, reason)
	print("RobloxServer: kicking '" .. Player.Name .. "': " .. reason)
	for _, Child in pairs(NetworkServer:children()) do
		local ok, owner = pcall(function() return Child:GetPlayer() end)
		if (ok and owner == Player) then
			delay(0.3, function() pcall(function() Child:CloseConnection() end) end)
		end
	end
end

-- The Noli myth (Code/Data/Noli.cs): the account named Noli leaves a black aura and turns everything
-- it stands on black, and anyone who says its name in the chat angers it.
local NoliPlayers = {}
local NoliAwake = false

local function IsNoli(name)
	return string.lower(name or "") == "noli"
end

local function Corrupt(Character)
	local torso = nil
	for i = 1, 50 do
		torso = FindChild(Character, "Torso")
		if (torso ~= nil) then
			break
		end
		wait(0.1)
	end
	if (torso == nil) then
		return
	end

	pcall(function()
		local aura = Instance.new("Smoke")
		aura.Name = "Void"
		aura.Color = Color3.new(0, 0, 0)
		aura.Opacity = 0.4
		aura.RiseVelocity = 1
		aura.Size = 3
		aura.Parent = torso
	end)

	local black = BrickColor.new(1003)
	for _, name in pairs({"Left Leg", "Right Leg"}) do
		local leg = FindChild(Character, name)
		if (leg ~= nil) then
			leg.Touched:connect(function(hit)
				pcall(function()
					local owner = hit.Parent
					if (owner == nil or owner == Character or FindChild(owner, "Humanoid") ~= nil) then
						return
					end
					if (hit:IsA("BasePart") and hit.BrickColor ~= black) then
						hit.BrickColor = black
					end
				end)
			end)
		end
	end
end

local function AngerNoli()
	if (NoliAwake) then
		return
	end
	NoliAwake = true

	local Lighting = game:GetService("Lighting")
	local saved = {}
	for _, property in pairs({"TimeOfDay", "Ambient", "FogColor", "FogEnd", "FogStart"}) do
		pcall(function() saved[property] = Lighting[property] end)
	end
	pcall(function() Lighting.TimeOfDay = "00:00:00" end)
	pcall(function() Lighting.Ambient = Color3.new(0, 0, 0) end)
	pcall(function() Lighting.FogColor = Color3.new(0, 0, 0) end)
	pcall(function() Lighting.FogStart = 0 end)
	pcall(function() Lighting.FogEnd = 40 end)

	local message = nil
	pcall(function()
		message = Instance.new("Message")
		message.Text = "You have angered Noli!"
		message.Parent = workspace
	end)
	wait(6)
	pcall(function() message:Remove() end)
	for property, value in pairs(saved) do
		pcall(function() Lighting[property] = value end)
	end

	wait(60)
	NoliAwake = false
end

local function Authenticate(Player)
	local value = nil
	for i = 1, 100 do
		value = FindChild(Player, "RSAuthTicket")
		if (value ~= nil and value.Value ~= "") then
			break
		end
		wait(0.1)
	end

	if (Player.Parent == nil) then
		return false
	end

	if (value == nil or value.Value == "") then
		if (RequireAuth) then
			Kick(Player, "No authentication ticket. Join this game with the Play button on the website.")
			return false
		end
		return true
	end

	local ticket = value.Value
	-- other clients can see the player's children, do not leave the ticket around
	pcall(function() value.Value = "" end)
	pcall(function() value.Parent = nil end)

	local answer = Request("Game/ValidateTicket.ashx?ticket=" .. ticket .. "&jobId=" .. JobId .. "&serverKey=" .. ServerKey)
	if (answer == nil or answer == "") then
		if (RequireAuth) then
			Kick(Player, "Could not reach the website to verify your account.")
			return false
		end
		return true
	end

	-- OK|userId|userName|superSafeChat|accountAge|isAdmin  or  ERROR|reason
	local fields = Split(answer)
	if (fields[1] ~= "OK") then
		Kick(Player, fields[2] or "Invalid authentication ticket.")
		return false
	end
	if (Player.Name ~= fields[3]) then
		Kick(Player, "Your name does not match your account (" .. fields[3] .. ").")
		return false
	end

	pcall(function() Player:SetSuperSafeChat(fields[4] == "true") end)
	pcall(function() Player:SetAccountAge(tonumber(fields[5]) or 0) end)
	-- the appearance comes from the website, not from what the client sent
	pcall(function() Player.CharacterAppearance = BaseUrl .. "Asset/CharacterFetch.ashx?userId=" .. fields[2] .. "&placeId=" .. PlaceId end)

	local userId = Instance.new("StringValue")
	userId.Name = "RSUserId"
	userId.Value = fields[2]
	userId.Parent = Player
	if (IsNoli(fields[3])) then
		NoliPlayers[Player] = true
	end
	print("RobloxServer: '" .. Player.Name .. "' authenticated as user " .. fields[2] .. ".")
	return true
end

Players.PlayerAdded:connect(function(Player)
	Player.CharacterAdded:connect(function(Character)
		if (NoliPlayers[Player]) then
			Corrupt(Character)
		end
	end)

	-- wait() cannot be used inside pcall in these clients, so run in a plain coroutine
	coroutine.resume(coroutine.create(function()
		if (Players.NumPlayers > MaxPlayers) then
			Kick(Player, "Too many players on server.")
			return
		end
		print("Player '" .. Player.Name .. "' with ID '" .. Player.userId .. "' added")
		if (Authenticate(Player)) then
			ReportPlayers()
			if (Players.CharacterAutoLoads) then
				pcall(function() Player:LoadCharacter() end)
			end
		end
	end))

	Player.Chatted:connect(function(message)
		print(Player.Name .. "; " .. message)
		local text = string.gsub(string.lower(message), "^%s*(.-)%s*$", "%1")
		if (IsNoli(text)) then
			coroutine.resume(coroutine.create(AngerNoli))
		end
	end)
end)

Players.PlayerRemoving:connect(function(Player)
	NoliPlayers[Player] = nil
	print("Player '" .. Player.Name .. "' with ID '" .. Player.userId .. "' leaving")
end)

-- NumPlayers still counts the player during PlayerRemoving, so report once it is gone.
Players.ChildRemoved:connect(function()
	delay(1, ReportPlayers)
end)

print("RobloxServer: job " .. JobId .. " for place " .. PlaceId .. " listening on port " .. Port .. (RequireAuth and " (tickets required)" or ""))
