-- RobloxServer join script for the 2012M and 2013M clients.
-- Generated by /Game/Join.ashx for one player and one game server, and started by RobloxPlayerLauncher.
-- The connection code follows the classic RBXPri / Novetus CSConnect function (MIT license).

local BaseUrl = [====[{BaseUrl}]====]
local ServerAddress = [====[{ServerAddress}]====]
local ServerPort = {ServerPort}
local PlaceId = {PlaceId}
local JobId = [====[{JobId}]====]
local UserId = {UserId}
local UserName = [====[{UserName}]====]
local AuthTicket = [====[{AuthTicket}]====]
local SuperSafeChat = {SuperSafeChat}
local AccountAge = {AccountAge}
local CharacterAppearance = [====[{CharacterAppearance}]====]
local PingUrl = [====[{PingUrl}]====]
local PingInterval = {PingInterval}

pcall(function() settings().Diagnostics:LegacyScriptMode() end)
pcall(function() game:GetService("ScriptContext").ScriptsDisabled = false end)
pcall(function() game:SetPlaceID(PlaceId, false) end)
pcall(function() game:GetService("ContentProvider"):SetBaseUrl(BaseUrl) end)
pcall(function() game:GetService("ScriptInformationProvider"):SetAssetUrl(BaseUrl .. "Asset/") end)
pcall(function() game:GetService("Players"):SetChatStyle(Enum.ChatStyle.ClassicAndBubble) end)
pcall(function() game:GetService("Visit"):SetUploadUrl("") end)
pcall(function() game:GetService("ChangeHistoryService"):SetEnabled(false) end)

-- Player list, chat, backpack... (content\scripts\cores in the client package). Runs in its own
-- thread so a client without the core scripts still plays.
delay(0, function() dofile("rbxasset://scripts\\cores\\StarterScript.lua") end)

-- (RunService:Run() now starts after the connection attempt, further down)
local NetworkClient = game:GetService("NetworkClient")
local Player = nil
local RequestingMarker = true

local function SetMessage(text)
	pcall(function() game:SetMessage(text) end)
end

local function RequestCharacter(Replicator)
	Player.Changed:connect(function(property)
		if (property == "Character") then
			pcall(function() game:ClearMessage() end)
		end
	end)
	SetMessage("Requesting character...")
	Replicator:RequestCharacter()
	SetMessage("Waiting for character...")
end

local function ConnectionAccepted(Peer, Replicator)
	Replicator.Disconnection:connect(function()
		SetMessage("You have lost connection to the game")
	end)
	pcall(function() game:SetMessageBrickCount() end)
	local Marker = Replicator:SendMarker()
	Marker.Received:connect(function()
		RequestingMarker = false
		RequestCharacter(Replicator)
	end)
	while RequestingMarker do
		pcall(function() workspace:ZoomToExtents() end)
		wait(0.5)
	end
end

local FailedHook = nil
NetworkClient.ConnectionAccepted:connect(ConnectionAccepted)
FailedHook = NetworkClient.ConnectionFailed:connect(function(Peer, Code)
	SetMessage("Failed to connect to the Game. (ID=" .. tostring(Code) .. ")")
end)
NetworkClient.ConnectionRejected:connect(function()
	pcall(function() FailedHook:disconnect() end)
	SetMessage("Failed to connect to the Game. (Connection rejected)")
end)

SetMessage("Connecting to server...")
pcall(function() NetworkClient.Ticket = AuthTicket end)

-- Older clients (2010) have no NetworkClient:PlayerConnect. The failed pcall then returns the error
-- MESSAGE (a string), which must never end up in Player: "TicketValue.Parent = Player" below would
-- throw and the client closes itself right after starting.
-- 2008-2010 clients document PlayerConnect(userId, server, port[, clientPort, threadSleepTime]): try both forms
-- and keep each error so a failure can say why.
-- Old clients speak IPv4 only: "::1", "localhost" or "::ffff:1.2.3.4" must become a plain IPv4 address.
pcall(function()
	local mapped = string.match(ServerAddress, "^::ffff:(%d+%.%d+%.%d+%.%d+)$")
	if (mapped) then ServerAddress = mapped end
	if (ServerAddress == "::1" or ServerAddress == "localhost" or ServerAddress == "") then ServerAddress = "127.0.0.1" end
end)

local connected, connectResult, playerConnectErrors = false, nil, ""
for attempt = 1, 3 do
	local ok, result
	if (attempt == 1) then
		ok, result = pcall(function() return NetworkClient:PlayerConnect(UserId, ServerAddress, ServerPort, 0, 20) end)
	elseif (attempt == 2) then
		ok, result = pcall(function() return NetworkClient:PlayerConnect(UserId, ServerAddress, ServerPort) end)
	else
		ok, result = pcall(function() return NetworkClient:PlayerConnect(UserId, ServerAddress, ServerPort, 0) end)
	end
	if (ok and type(result) == "userdata") then
		connected, connectResult = true, result
		break
	end
	playerConnectErrors = playerConnectErrors .. tostring(result) .. " | "
	-- A failed call can leave a half-made local player behind, and the next call then fails with
	-- "Local player already exists": remove it before trying again.
	pcall(function()
		local lp = game:GetService("Players").LocalPlayer
		if (lp) then
			pcall(function() lp:Remove() end)
			pcall(function() lp:remove() end)
		end
	end)
end
if (connected) then
	Player = connectResult
else
	pcall(function() Player = game:GetService("Players"):CreateLocalPlayer(UserId) end)
	if (type(Player) ~= "userdata") then
		Player = nil
		-- "Local player already exists": use the one the client already made.
		pcall(function() Player = game:GetService("Players").LocalPlayer end)
	end
	-- Connect even if the local player could not be created (it used to share one pcall with CreateLocalPlayer).
	-- 2012/2013 take (address, port); the 2008-2010 clients want (address, port, clientPort, threadSleepTime).
	local ok, connectError = pcall(function() NetworkClient:Connect(ServerAddress, ServerPort) end)
	if (not ok) then
		local ok2, connectError2 = pcall(function() NetworkClient:Connect(ServerAddress, ServerPort, 0, 20) end)
		if (ok2) then
			ok = true
		else
			connectError = tostring(connectError) .. " | " .. tostring(connectError2)
		end
	end
	if (not ok) then
		SetMessage("Failed to connect to the Game. (" .. ServerAddress .. ":" .. tostring(ServerPort) .. " " .. string.sub(playerConnectErrors, 1, 90) .. ")")
	end
end

-- EXPERIMENT: Run() used to be called before PlayerConnect; a client that is already running a local game
-- may refuse to open the network connection. Start it only once the connection attempt is over.
pcall(function() game:GetService("RunService"):Run() end)

pcall(function() Player.Name = UserName end)
pcall(function() Player:SetSuperSafeChat(SuperSafeChat) end)
pcall(function() Player:SetUnder13(SuperSafeChat) end)
pcall(function() Player:SetAccountAge(AccountAge) end)
pcall(function() Player:SetMembershipType(Enum.MembershipType.None) end)
pcall(function() Player.CharacterAppearance = CharacterAppearance end)

-- The one-time ticket from PlaceLauncher.ashx. It replicates to the game server, which checks it
-- with /Game/ValidateTicket.ashx and kicks players without a valid ticket.
local TicketValue = Instance.new("StringValue")
TicketValue.Name = "RSAuthTicket"
TicketValue.Value = AuthTicket
if (type(Player) == "userdata") then
	pcall(function() TicketValue.Parent = Player end)
end

-- Tells the website this player is still here (Game/ClientPresence.ashx).
if (PingUrl ~= "") then
	delay(0, function()
		while true do
			pcall(function() game:HttpGet(PingUrl .. "&UserID=" .. UserId, true) end)
			wait(PingInterval)
		end
	end)
end
