-- RobloxServer join script for the 2012M and 2013M clients.
-- Generated by /Game/Join.ashx for one player and one game server, and started by RobloxPlayerLauncher.
-- The connection code follows the classic RBXPri / Novetus CSConnect function (MIT license).

local BaseUrl = [====[{BaseUrl}]====]
local ServerAddress = [====[{ServerAddress}]====]
local ServerPort = {ServerPort}
local PlaceId = {PlaceId}
local JobId = [====[{JobId}]====]
local UserId = {UserId}
local UserName = [====[{UserName}]====]
local AuthTicket = [====[{AuthTicket}]====]
local SuperSafeChat = {SuperSafeChat}
local AccountAge = {AccountAge}
local CharacterAppearance = [====[{CharacterAppearance}]====]
local PingUrl = [====[{PingUrl}]====]
local PingInterval = {PingInterval}

pcall(function() settings().Diagnostics:LegacyScriptMode() end)
pcall(function() game:GetService("ScriptContext").ScriptsDisabled = false end)
pcall(function() game:SetPlaceID(PlaceId, false) end)
pcall(function() game:GetService("ContentProvider"):SetBaseUrl(BaseUrl) end)
pcall(function() game:GetService("ScriptInformationProvider"):SetAssetUrl(BaseUrl .. "Asset/") end)
pcall(function() game:GetService("Players"):SetChatStyle(Enum.ChatStyle.ClassicAndBubble) end)
pcall(function() game:GetService("Visit"):SetUploadUrl("") end)
pcall(function() game:GetService("ChangeHistoryService"):SetEnabled(false) end)

-- Player list, chat, backpack... (content\scripts\cores in the client package). Runs in its own
-- thread so a client without the core scripts still plays.
delay(0, function() dofile("rbxasset://scripts\\cores\\StarterScript.lua") end)

game:GetService("RunService"):Run()

local NetworkClient = game:GetService("NetworkClient")
local Player = nil
local RequestingMarker = true

local function SetMessage(text)
	pcall(function() game:SetMessage(text) end)
end

local function RequestCharacter(Replicator)
	Player.Changed:connect(function(property)
		if (property == "Character") then
			pcall(function() game:ClearMessage() end)
		end
	end)
	SetMessage("Requesting character...")
	Replicator:RequestCharacter()
	SetMessage("Waiting for character...")
end

local function ConnectionAccepted(Peer, Replicator)
	Replicator.Disconnection:connect(function()
		SetMessage("You have lost connection to the game")
	end)
	pcall(function() game:SetMessageBrickCount() end)
	local Marker = Replicator:SendMarker()
	Marker.Received:connect(function()
		RequestingMarker = false
		RequestCharacter(Replicator)
	end)
	while RequestingMarker do
		pcall(function() workspace:ZoomToExtents() end)
		wait(0.5)
	end
end

local FailedHook = nil
NetworkClient.ConnectionAccepted:connect(ConnectionAccepted)
FailedHook = NetworkClient.ConnectionFailed:connect(function(Peer, Code)
	SetMessage("Failed to connect to the Game. (ID=" .. tostring(Code) .. ")")
end)
NetworkClient.ConnectionRejected:connect(function()
	pcall(function() FailedHook:disconnect() end)
	SetMessage("Failed to connect to the Game. (Connection rejected)")
end)

SetMessage("Connecting to server...")
pcall(function() NetworkClient.Ticket = AuthTicket end)

local connected
connected, Player = pcall(function() return NetworkClient:PlayerConnect(UserId, ServerAddress, ServerPort) end)
if (not connected) then
	local ok = pcall(function()
		Player = game:GetService("Players"):CreateLocalPlayer(UserId)
		NetworkClient:Connect(ServerAddress, ServerPort)
	end)
	if (not ok) then
		SetMessage("Failed to connect to the Game.")
	end
end

pcall(function() Player.Name = UserName end)
pcall(function() Player:SetSuperSafeChat(SuperSafeChat) end)
pcall(function() Player:SetUnder13(SuperSafeChat) end)
pcall(function() Player:SetAccountAge(AccountAge) end)
pcall(function() Player:SetMembershipType(Enum.MembershipType.None) end)
pcall(function() Player.CharacterAppearance = CharacterAppearance end)

-- The one-time ticket from PlaceLauncher.ashx. It replicates to the game server, which checks it
-- with /Game/ValidateTicket.ashx and kicks players without a valid ticket.
local TicketValue = Instance.new("StringValue")
TicketValue.Name = "RSAuthTicket"
TicketValue.Value = AuthTicket
TicketValue.Parent = Player

-- Tells the website this player is still here (Game/ClientPresence.ashx).
if (PingUrl ~= "") then
	delay(0, function()
		while true do
			pcall(function() game:HttpGet(PingUrl .. "&UserID=" .. UserId, true) end)
			wait(PingInterval)
		end
	end)
end
