//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobloxServer.Pages
{
    public partial class MyCharacter
    {
        protected global::System.Web.UI.HtmlControls.HtmlImage AvatarImage;
        protected global::System.Web.UI.WebControls.PlaceHolder VoidPanel;
        protected global::System.Web.UI.WebControls.PlaceHolder ColorsPanel;
        protected global::System.Web.UI.WebControls.Repeater PartsRepeater;
        protected global::System.Web.UI.WebControls.Repeater PaletteRepeater;
        protected global::System.Web.UI.WebControls.HiddenField PartField;
        protected global::System.Web.UI.WebControls.HiddenField ColorField;
        protected global::System.Web.UI.WebControls.Button SaveColorButton;
    }
}
