//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobloxServer.Pages
{
    public partial class MyHome
    {
        protected global::System.Web.UI.WebControls.Literal NameLiteral;
        protected global::System.Web.UI.HtmlControls.HtmlImage AvatarImage;
        protected global::System.Web.UI.WebControls.Repeater PeopleRepeater;
        protected global::System.Web.UI.WebControls.Panel StatusPanel;
        protected global::System.Web.UI.WebControls.TextBox StatusBox;
        protected global::System.Web.UI.WebControls.Button ShareButton;
        protected global::System.Web.UI.WebControls.Label StatusError;
        protected global::System.Web.UI.WebControls.PlaceHolder EmptyFeed;
        protected global::System.Web.UI.WebControls.Repeater FeedRepeater;
        protected global::System.Web.UI.WebControls.PlaceHolder NoRecent;
        protected global::System.Web.UI.WebControls.Repeater RecentRepeater;
        protected global::System.Web.UI.WebControls.Repeater NewsRepeater;
    }
}
