//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobloxServer.Pages
{
    public partial class Admin
    {
        protected global::System.Web.UI.WebControls.Label MessageLabel;
        protected global::System.Web.UI.WebControls.TextBox BanUserBox;
        protected global::System.Web.UI.WebControls.TextBox BanReasonBox;
        protected global::System.Web.UI.WebControls.TextBox BanDaysBox;
        protected global::System.Web.UI.WebControls.Button BanButton;
        protected global::System.Web.UI.WebControls.Button UnbanButton;
        protected global::System.Web.UI.WebControls.Button MakeAdminButton;
        protected global::System.Web.UI.WebControls.TextBox IpBox;
        protected global::System.Web.UI.WebControls.TextBox IpReasonBox;
        protected global::System.Web.UI.WebControls.Button IpBanButton;
        protected global::System.Web.UI.WebControls.Button IpUnbanButton;
        protected global::System.Web.UI.WebControls.Repeater IpBansRepeater;
        protected global::System.Web.UI.WebControls.Repeater UsersRepeater;
        protected global::System.Web.UI.WebControls.Repeater ServersRepeater;
        protected global::System.Web.UI.WebControls.Repeater ClientsRepeater;
        protected global::System.Web.UI.WebControls.DropDownList PackageList;
        protected global::System.Web.UI.WebControls.FileUpload PackageUpload;
        protected global::System.Web.UI.WebControls.Button PackageUploadButton;
        protected global::System.Web.UI.WebControls.Label PackageMessage;
        protected global::System.Web.UI.WebControls.Literal PublicKeyLiteral;
    }
}
