//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobloxServer.Pages
{
    public partial class Browse
    {
        protected global::System.Web.UI.WebControls.Panel SearchPanel;
        protected global::System.Web.UI.WebControls.TextBox NameBox;
        protected global::System.Web.UI.WebControls.Button SearchButton;
        protected global::System.Web.UI.WebControls.PlaceHolder NoResults;
        protected global::System.Web.UI.WebControls.Literal QueryLiteral;
        protected global::System.Web.UI.WebControls.Repeater UsersRepeater;
    }
}
