//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobloxServer.Pages
{
    public partial class Develop
    {
        protected global::System.Web.UI.WebControls.TextBox NameBox;
        protected global::System.Web.UI.WebControls.TextBox DescriptionBox;
        protected global::System.Web.UI.WebControls.DropDownList GenreList;
        protected global::System.Web.UI.WebControls.DropDownList ClientList;
        protected global::System.Web.UI.WebControls.TextBox MaxPlayersBox;
        protected global::System.Web.UI.WebControls.CheckBox PublicBox;
        protected global::System.Web.UI.WebControls.CheckBox FilteringBox;
        protected global::System.Web.UI.WebControls.FileUpload PlaceUpload;
        protected global::System.Web.UI.WebControls.Label ErrorLabel;
        protected global::System.Web.UI.WebControls.Button PublishButton;
        protected global::System.Web.UI.WebControls.PlaceHolder NoPlaces;
        protected global::System.Web.UI.WebControls.Repeater MyPlacesRepeater;
    }
}
