//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobloxServer.Pages
{
    public partial class Landing
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm LandingForm;
        protected global::System.Web.UI.WebControls.Panel LoginPanel;
        protected global::System.Web.UI.WebControls.TextBox loginUsername;
        protected global::System.Web.UI.WebControls.TextBox loginPassword;
        protected global::System.Web.UI.WebControls.Button LoginButton;
        protected global::System.Web.UI.WebControls.Panel SignupPanel;
        protected global::System.Web.UI.WebControls.DropDownList lstMonths;
        protected global::System.Web.UI.WebControls.DropDownList lstDays;
        protected global::System.Web.UI.WebControls.DropDownList lstYears;
        protected global::System.Web.UI.WebControls.RadioButton MaleBtn;
        protected global::System.Web.UI.WebControls.RadioButton FemaleBtn;
        protected global::System.Web.UI.WebControls.TextBox username;
        protected global::System.Web.UI.WebControls.TextBox password;
        protected global::System.Web.UI.WebControls.TextBox passwordConfirm;
        protected global::System.Web.UI.WebControls.Button SignUpButton;
    }
}
