//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobloxServer.Pages
{
    public partial class Login
    {
        protected global::System.Web.UI.WebControls.Panel LoginPanel;
        protected global::System.Web.UI.WebControls.TextBox UserNameBox;
        protected global::System.Web.UI.WebControls.TextBox PasswordBox;
        protected global::System.Web.UI.WebControls.Label ErrorLabel;
        protected global::System.Web.UI.WebControls.Button LoginButton;
    }
}
