//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobloxServer.Pages
{
    public partial class NotApproved
    {
        protected global::System.Web.UI.WebControls.Literal TitleLiteral;
        protected global::System.Web.UI.WebControls.Literal ReasonLiteral;
        protected global::System.Web.UI.WebControls.PlaceHolder ReactivatePanel;
        protected global::System.Web.UI.WebControls.CheckBox AgreeBox;
        protected global::System.Web.UI.WebControls.Button ReactivateButton;
    }
}
