//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobloxServer.Pages
{
    public partial class PlaceItem
    {
        protected global::System.Web.UI.WebControls.PlaceHolder NotFoundPanel;
        protected global::System.Web.UI.WebControls.PlaceHolder PlacePanel;
        protected global::System.Web.UI.WebControls.Literal NameLiteral;
        protected global::System.Web.UI.WebControls.Literal CreatorLiteral;
        protected global::System.Web.UI.WebControls.Literal ClientLiteral;
        protected global::System.Web.UI.WebControls.Literal VisitsLiteral;
        protected global::System.Web.UI.WebControls.Literal UpdatedLiteral;
        protected global::System.Web.UI.WebControls.Literal DescriptionLiteral;
        protected global::System.Web.UI.WebControls.Literal NameLiteral2;
        protected global::System.Web.UI.WebControls.Literal IdLiteral;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor DownloadLink;
        protected global::System.Web.UI.WebControls.PlaceHolder NoServers;
        protected global::System.Web.UI.WebControls.Repeater ServersRepeater;
        protected global::System.Web.UI.WebControls.PlaceHolder EditPanel;
        protected global::System.Web.UI.WebControls.TextBox NameBox;
        protected global::System.Web.UI.WebControls.TextBox DescriptionBox;
        protected global::System.Web.UI.WebControls.DropDownList ClientList;
        protected global::System.Web.UI.WebControls.TextBox MaxPlayersBox;
        protected global::System.Web.UI.WebControls.CheckBox PublicBox;
        protected global::System.Web.UI.WebControls.CheckBox FilteringBox;
        protected global::System.Web.UI.WebControls.FileUpload PlaceUpload;
        protected global::System.Web.UI.WebControls.Label ErrorLabel;
        protected global::System.Web.UI.WebControls.Button SaveButton;
        protected global::System.Web.UI.WebControls.Button DeleteButton;
    }
}
