//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobloxServer.Pages
{
    public partial class Register
    {
        protected global::System.Web.UI.WebControls.Panel RegisterPanel;
        protected global::System.Web.UI.WebControls.TextBox UserNameBox;
        protected global::System.Web.UI.WebControls.TextBox PasswordBox;
        protected global::System.Web.UI.WebControls.TextBox ConfirmBox;
        protected global::System.Web.UI.WebControls.CheckBox Under13Box;
        protected global::System.Web.UI.WebControls.Label ErrorLabel;
        protected global::System.Web.UI.WebControls.Button RegisterButton;
        protected global::System.Web.UI.WebControls.PlaceHolder ClosedMessage;
    }
}
