//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobloxServer.Pages
{
    public partial class UserProfile
    {
        protected global::System.Web.UI.WebControls.PlaceHolder NotFoundPanel;
        protected global::System.Web.UI.WebControls.PlaceHolder ProfilePanel;
        protected global::System.Web.UI.WebControls.Literal HeaderLiteral;
        protected global::System.Web.UI.WebControls.Literal StatusLiteral;
        protected global::System.Web.UI.WebControls.Literal UrlLiteral;
        protected global::System.Web.UI.HtmlControls.HtmlImage AvatarImage;
        protected global::System.Web.UI.WebControls.Literal JoinedLiteral;
        protected global::System.Web.UI.WebControls.Literal LastOnlineLiteral;
        protected global::System.Web.UI.WebControls.Literal VisitsLiteral;
        protected global::System.Web.UI.WebControls.PlaceHolder AdminBadge;
        protected global::System.Web.UI.WebControls.PlaceHolder NoPlaces;
        protected global::System.Web.UI.WebControls.Literal NoPlacesLiteral;
        protected global::System.Web.UI.WebControls.Repeater PlacesRepeater;
    }
}
