//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobloxServer.Pages
{
    public partial class VoidPage
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm VoidForm;
        protected global::System.Web.UI.WebControls.PlaceHolder AskPanel;
        protected global::System.Web.UI.WebControls.Literal RiddleLiteral;
        protected global::System.Web.UI.WebControls.Panel SpeakPanel;
        protected global::System.Web.UI.WebControls.TextBox AnswerBox;
        protected global::System.Web.UI.WebControls.Button SpeakButton;
        protected global::System.Web.UI.WebControls.Label AngeredLabel;
        protected global::System.Web.UI.WebControls.PlaceHolder RevealPanel;
        protected global::System.Web.UI.WebControls.Literal WhisperLiteral;
    }
}
