#!/bin/bash
# RobloxServer - Raspberry Pi Zero 2W gateway installer (Raspberry Pi OS Lite, Bookworm).
#
#   1. edit pi/robloxserver-pi.conf
#   2. sudo ./install.sh
#
# RENDER_ONLY=1 ./install.sh   writes every generated file to pi/out/ without touching the system.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(dirname "$HERE")"
CONF="${RS_CONF:-$HERE/robloxserver-pi.conf}"
RENDER_ONLY="${RENDER_ONLY:-}"
OUT="$HERE/out"

# shellcheck source=/dev/null
. "$CONF"

if [ -z "$RENDER_ONLY" ] && [ "$(id -u)" -ne 0 ]; then
    echo "Run as root: sudo ./install.sh" >&2
    exit 1
fi

case "$SITE_MODE" in
    local|remote) ;;
    *) echo "SITE_MODE must be 'local' or 'remote'" >&2; exit 1 ;;
esac

# Path on the system, or under pi/out when rendering only.
target() {
    local path="$1"
    if [ -n "$RENDER_ONLY" ]; then
        path="$OUT$path"
    fi
    mkdir -p "$(dirname "$path")"
    echo "$path"
}

render() {
    sed -e "s|@HTTP_PORT@|$HTTP_PORT|g" \
        -e "s|@SITE_HOST@|$SITE_HOST|g" \
        -e "s|@SITE_PORT@|$SITE_PORT|g" \
        -e "s|@SITE_DIR@|$SITE_DIR|g" \
        "$HERE/templates/$1" > "$(target "$2")"
}

run() {
    if [ -n "$RENDER_ONLY" ]; then
        echo "[render-only] $*"
    else
        "$@"
    fi
}

echo "==> Packages"
packages=(nginx miniupnpc curl iptables)
[ "$DNS_ENABLED" = "yes" ] && packages+=(dnsmasq)
[ "$SITE_MODE" = "local" ] && packages+=(mono-complete mono-fastcgi-server4 rsync)
run apt-get update
run env DEBIAN_FRONTEND=noninteractive apt-get install -y "${packages[@]}"

echo "==> Configuration and scripts"
cp "$CONF" "$(target /etc/robloxserver/robloxserver-pi.conf)"
install -m 0755 "$HERE/bin/rs-firewall.sh" "$(target /usr/local/sbin/rs-firewall.sh)"
install -m 0755 "$HERE/bin/rs-upnp.sh" "$(target /usr/local/sbin/rs-upnp.sh)"

echo "==> nginx ($SITE_MODE)"
render "nginx-$SITE_MODE.conf" /etc/nginx/sites-available/robloxserver
if [ -z "$RENDER_ONLY" ]; then
    ln -sf /etc/nginx/sites-available/robloxserver /etc/nginx/sites-enabled/robloxserver
    rm -f /etc/nginx/sites-enabled/default
fi

if [ "$SITE_MODE" = "local" ]; then
    echo "==> Building and publishing RobloxServer.Web to $SITE_DIR (Mono)"
    render robloxserver-fastcgi.service /etc/systemd/system/robloxserver-fastcgi.service
    if [ -z "$RENDER_ONLY" ]; then
        (cd "$REPO/RobloxServer.Web" && xbuild /nologo /v:minimal /p:Configuration=Release RobloxServer.Web.csproj)
        mkdir -p "$SITE_DIR/App_Data"
        # Code is replaced, data (users, places, keys, logs) is kept.
        rsync -a --delete --exclude obj/ --exclude App_Data/ "$REPO/RobloxServer.Web/" "$SITE_DIR/"
        rsync -a --ignore-existing "$REPO/RobloxServer.Web/App_Data/" "$SITE_DIR/App_Data/"
        rsync -a "$REPO/RobloxServer.Web/App_Data/Templates/" "$SITE_DIR/App_Data/Templates/"
        chown -R www-data:www-data "$SITE_DIR"
    fi
fi

if [ "$DNS_ENABLED" = "yes" ]; then
    echo "==> dnsmasq: ${DNS_HOSTS} -> $PI_IP"
    dns="$(target /etc/dnsmasq.d/robloxserver.conf)"
    {
        echo "# RobloxServer - generated by install.sh"
        echo "no-resolv"
        for server in $DNS_UPSTREAM; do echo "server=$server"; done
        # host-record only answers the exact name, so assetdelivery.roblox.com and friends
        # still resolve to the real Roblox (the server uses them as an asset fallback).
        for host in $DNS_HOSTS; do echo "host-record=$host,$PI_IP"; done
    } > "$dns"
fi

echo "==> systemd units"
render robloxserver-firewall.service /etc/systemd/system/robloxserver-firewall.service
render robloxserver-upnp.service /etc/systemd/system/robloxserver-upnp.service
render robloxserver-upnp.timer /etc/systemd/system/robloxserver-upnp.timer

run systemctl daemon-reload
run nginx -t
run systemctl enable --now robloxserver-firewall.service
run systemctl restart robloxserver-firewall.service
run systemctl enable --now robloxserver-upnp.timer
run systemctl start robloxserver-upnp.service
if [ "$SITE_MODE" = "local" ]; then
    run systemctl enable --now robloxserver-fastcgi.service
    run systemctl restart robloxserver-fastcgi.service
fi
if [ "$DNS_ENABLED" = "yes" ]; then
    run systemctl enable dnsmasq
    run systemctl restart dnsmasq
fi
run systemctl reload nginx

cat <<SUMMARY

RobloxServer gateway ready on $PI_IP.
  Web:   http://$PI_IP:$HTTP_PORT/  ->  $( [ "$SITE_MODE" = "remote" ] && echo "IIS at $SITE_HOST:$SITE_PORT" || echo "Mono in $SITE_DIR" )
  Games: $GAME_FORWARDS ($GAME_PROTOCOLS)
  DNS:   $( [ "$DNS_ENABLED" = "yes" ] && echo "set the router's DHCP DNS server to $PI_IP" || echo "disabled" )
$( [ "$SITE_MODE" = "remote" ] && echo "  IIS:   add $PI_IP to TrustedProxies in Web.config so real player IPs are used for bans and limits." )
  Set PublicGameAddress in Web.config to your public IP or DDNS name.
SUMMARY
